// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
lv_obj_t *ui_mainScreen;
void ui_event_Label4( lv_event_t * e);
lv_obj_t *ui_Label4;
lv_obj_t *ui_status_label;
void ui_event_wifiIcon( lv_event_t * e);
lv_obj_t *ui_wifiIcon;
void ui_event_noWifiIcon( lv_event_t * e);
lv_obj_t *ui_noWifiIcon;
lv_obj_t *ui_countLabel;
void ui_event_setupButton1( lv_event_t * e);
lv_obj_t *ui_setupButton1;
lv_obj_t *ui_timeLabel;
lv_obj_t *ui_sdErrorLogo;
lv_obj_t *ui_sdLogo;


// SCREEN: ui_setupScreen
void ui_setupScreen_screen_init(void);
lv_obj_t *ui_setupScreen;
void ui_event_mainTab( lv_event_t * e);
lv_obj_t *ui_mainTab;
void ui_event_TabPage1WiFi( lv_event_t * e);
lv_obj_t *ui_TabPage1WiFi;
lv_obj_t *ui_ssidLabel;
void ui_event_ssidDropdown( lv_event_t * e);
lv_obj_t *ui_ssidDropdown;
lv_obj_t *ui_passLabel;
void ui_event_passTextarea( lv_event_t * e);
lv_obj_t *ui_passTextarea;
void ui_event_connectButton( lv_event_t * e);
lv_obj_t *ui_connectButton;
lv_obj_t *ui_connectButtonlabel;
void ui_event_scanButton( lv_event_t * e);
lv_obj_t *ui_scanButton;
lv_obj_t *ui_scanButtonlabel;
void ui_event_econButton( lv_event_t * e);
lv_obj_t *ui_econButton;
lv_obj_t *ui_econButtonlabel;
lv_obj_t *ui_connectFromEEPROMLabel;
void ui_event_TabPage2BT( lv_event_t * e);
lv_obj_t *ui_TabPage2BT;
lv_obj_t *ui_BtLabel;
void ui_event_BtTextArea( lv_event_t * e);
lv_obj_t *ui_BtTextArea;
lv_obj_t *ui_BtBitrateLabel;
void ui_event_BtBitrateDropdown( lv_event_t * e);
lv_obj_t *ui_BtBitrateDropdown;
void ui_event_BtSave( lv_event_t * e);
lv_obj_t *ui_BtSave;
lv_obj_t *ui_label20;
void ui_event_BtStop( lv_event_t * e);
lv_obj_t *ui_BtStop;
lv_obj_t *ui_label1;
void ui_event_BtStart( lv_event_t * e);
lv_obj_t *ui_BtStart;
lv_obj_t *ui_label2;
void ui_event_TabPage3RFID( lv_event_t * e);
lv_obj_t *ui_TabPage3RFID;
lv_obj_t *ui_deviceIDlabel;
lv_obj_t *ui_versionLabel;
lv_obj_t *ui_minfLabel;
lv_obj_t *ui_protocolLabel;
lv_obj_t *ui_baudLabel;
void ui_event_baudDD( lv_event_t * e);
lv_obj_t *ui_baudDD;
lv_obj_t *ui_maxfLabel;
lv_obj_t *ui_antennaLabel;
lv_obj_t *ui_readertypeLabel;
lv_obj_t *ui_bandLabel;
void ui_event_banadDD( lv_event_t * e);
lv_obj_t *ui_banadDD;
lv_obj_t *ui_powerLabel;
void ui_event_powerTextarea( lv_event_t * e);
lv_obj_t *ui_powerTextarea;
lv_obj_t *ui_scantimeLabel;
void ui_event_scantimeTextarea( lv_event_t * e);
lv_obj_t *ui_scantimeTextarea;
lv_obj_t *ui_beeponSwitch;
lv_obj_t *ui_beeponLabel;
void ui_event_writeButton( lv_event_t * e);
lv_obj_t *ui_writeButton;
lv_obj_t *ui_writeButtonlabel;
lv_obj_t *ui_deviceIDlabel1;
lv_obj_t *ui_versionLabel1;
lv_obj_t *ui_antennaLabel1;
lv_obj_t *ui_maxfLabel1;
lv_obj_t *ui_minfLabel1;
lv_obj_t *ui_protocolLabel1;
lv_obj_t *ui_notifyPanelOnRFIDTab;
void ui_event_notifyPanelclosebutton2( lv_event_t * e);
lv_obj_t *ui_notifyPanelclosebutton2;
lv_obj_t *ui_notifyPanelclosebuttonlabel2;
lv_obj_t *ui_notifyPanellabel2;
lv_obj_t *ui_TabPage4Audio;
lv_obj_t *ui_audioLabel;
void ui_event_musicDropdown( lv_event_t * e);
lv_obj_t *ui_musicDropdown;
void ui_event_playButton( lv_event_t * e);
lv_obj_t *ui_playButton;
lv_obj_t *ui_playButtonLabel;
void ui_event_stopButton( lv_event_t * e);
lv_obj_t *ui_stopButton;
lv_obj_t *ui_stopLabel;
void ui_event_killMusicTask( lv_event_t * e);
lv_obj_t *ui_killMusicTask;
lv_obj_t *ui_musicInfoLabel;
void ui_event_musicScanButton( lv_event_t * e);
lv_obj_t *ui_musicScanButton;
lv_obj_t *ui_searchMusiclabel;
lv_obj_t *ui_TabPage5Server;
void ui_event_TabPage6Setup( lv_event_t * e);
lv_obj_t *ui_TabPage6Setup;
void ui_event_saveScanData( lv_event_t * e);
lv_obj_t *ui_saveScanData;
lv_obj_t *ui_sleepAfterLabel;
void ui_event_sleepAfterTextarea( lv_event_t * e);
lv_obj_t *ui_sleepAfterTextarea;
lv_obj_t *ui_saveScanDataLabel;
lv_obj_t *ui_notifyPanelOnSetupTab;
void ui_event_notifyPanelclosebutton1( lv_event_t * e);
lv_obj_t *ui_notifyPanelclosebutton1;
lv_obj_t *ui_notifyPanelclosebuttonlabel1;
lv_obj_t *ui_notifyPanellabel1;
void ui_event_writeButtonSetupTab( lv_event_t * e);
lv_obj_t *ui_writeButtonSetupTab;
lv_obj_t *ui_writeButtonlabel1;
lv_obj_t *ui_notifyPanel;
void ui_event_notifyPanelclosebutton( lv_event_t * e);
lv_obj_t *ui_notifyPanelclosebutton;
lv_obj_t *ui_notifyPanelclosebuttonlabel;
lv_obj_t *ui_notifyPanellabel;
lv_obj_t *ui_primaryKeyboard;
void ui_event_home( lv_event_t * e);
lv_obj_t *ui_home;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_settings[1] = {&ui_img_settings11_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Label4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_setupScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_setupScreen_screen_init);
}
}
void ui_event_wifiIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      wifi_icon_clicked( e );
}
}
void ui_event_noWifiIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      no_wifi_icon_clicked( e );
}
}
void ui_event_setupButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_delete( &ui_mainScreen);
      _ui_screen_change( &ui_setupScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_setupScreen_screen_init);
}
}
void ui_event_mainTab( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TabPage1WiFi( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_ssidDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      ssid_dropdown_vchanged( e );
}
}
void ui_event_passTextarea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_connectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      connect_function( e );
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_scanButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      scan_function( e );
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_econButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      eeprom_connect( e );
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TabPage2BT( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_BtTextArea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_primaryKeyboard,  ui_BtTextArea);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_BtBitrateDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      bt_bitrate_dd_vchanged( e );
}
}
void ui_event_BtSave( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      save_bt_( e );
}
}
void ui_event_BtStop( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      stop_bt_( e );
}
}
void ui_event_BtStart( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      start_bt_( e );
}
}
void ui_event_TabPage3RFID( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_baudDD( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      rfid_baud_dd_vchanged( e );
}
}
void ui_event_banadDD( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      rfid_band_dd_vchanged( e );
}
}
void ui_event_powerTextarea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_primaryKeyboard,  ui_powerTextarea);
}
}
void ui_event_scantimeTextarea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_primaryKeyboard,  ui_scantimeTextarea);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_writeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      write_rfid( e );
}
}
void ui_event_notifyPanelclosebutton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_notifyPanelOnRFIDTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_musicDropdown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      audio_dd_value_changed( e );
}
}
void ui_event_playButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      play_music( e );
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_stopButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      stop_music( e );
}
}
void ui_event_killMusicTask( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      kill_audio_task( e );
}
}
void ui_event_musicScanButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      search_music( e );
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_TabPage6Setup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_saveScanData( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      save_to_sd_btn_clicked( e );
}
}
void ui_event_sleepAfterTextarea( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_primaryKeyboard,  ui_sleepAfterTextarea);
      _ui_flag_modify( ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}
void ui_event_notifyPanelclosebutton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_notifyPanelOnSetupTab, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_writeButtonSetupTab( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      write_setup( e );
}
}
void ui_event_notifyPanelclosebutton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_flag_modify( ui_notifyPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_home( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_mainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_mainScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_mainScreen_screen_init();
ui_setupScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_mainScreen);
}
