// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#ifndef _HANDHELD_GUI_V1_1_UI_H
#define _HANDHELD_GUI_V1_1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_mainScreen
void ui_mainScreen_screen_init(void);
extern lv_obj_t * ui_mainScreen;
void ui_event_Label4(lv_event_t * e);
extern lv_obj_t * ui_Label4;
void ui_event_wifiIcon(lv_event_t * e);
extern lv_obj_t * ui_wifiIcon;
void ui_event_noWifiIcon(lv_event_t * e);
extern lv_obj_t * ui_noWifiIcon;
extern lv_obj_t * ui_countLabel;
void ui_event_setupButton1(lv_event_t * e);
extern lv_obj_t * ui_setupButton1;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_sdLogo;
void ui_event_mergeSwitch(lv_event_t * e);
extern lv_obj_t * ui_mergeSwitch;
void ui_event_memBtn(lv_event_t * e);
extern lv_obj_t * ui_memBtn;
extern lv_obj_t * ui_memBtnLabel;
extern lv_obj_t * ui_MemPanel;
extern lv_obj_t * ui_testbtn;
extern lv_obj_t * ui_econButtonlabel3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_chipType;
extern lv_obj_t * ui_chipTypeLabel;
extern lv_obj_t * ui_epcSize;
extern lv_obj_t * ui_epcSizeLabel1;
extern lv_obj_t * ui_epcSizeLabel2;
extern lv_obj_t * ui_totalMem;
extern lv_obj_t * ui_totatMemoryLabel1;
extern lv_obj_t * ui_totatMemoryLabel2;
extern lv_obj_t * ui_tidSize;
extern lv_obj_t * ui_TIDsizeLabel1;
extern lv_obj_t * ui_TIDsizeLabel2;
extern lv_obj_t * ui_PWDsize;
extern lv_obj_t * ui_Usersize;
extern lv_obj_t * ui_userSizeLabel1;
extern lv_obj_t * ui_userSizeLabel2;
extern lv_obj_t * ui_PWDsizeLabel3;
extern lv_obj_t * ui_PWDsizeLabel4;
void ui_event_panelClose(lv_event_t * e);
extern lv_obj_t * ui_panelClose;
extern lv_obj_t * ui_econButtonlabel1;
extern lv_obj_t * ui_testbtn1;
extern lv_obj_t * ui_econButtonlabel4;
extern lv_obj_t * ui_testbtn2;
extern lv_obj_t * ui_econButtonlabel5;
extern lv_obj_t * ui_testbtn3;
extern lv_obj_t * ui_econButtonlabel6;
extern lv_obj_t * ui_testbtn4;
extern lv_obj_t * ui_econButtonlabel7;
// SCREEN: ui_setupScreen
void ui_setupScreen_screen_init(void);
extern lv_obj_t * ui_setupScreen;
void ui_event_mainTab(lv_event_t * e);
extern lv_obj_t * ui_mainTab;
void ui_event_TabPage1WiFi(lv_event_t * e);
extern lv_obj_t * ui_TabPage1WiFi;
extern lv_obj_t * ui_ssidLabel;
void ui_event_ssidDropdown(lv_event_t * e);
extern lv_obj_t * ui_ssidDropdown;
extern lv_obj_t * ui_passLabel;
void ui_event_passTextarea(lv_event_t * e);
extern lv_obj_t * ui_passTextarea;
void ui_event_connectButton(lv_event_t * e);
extern lv_obj_t * ui_connectButton;
extern lv_obj_t * ui_connectButtonlabel;
void ui_event_scanButton(lv_event_t * e);
extern lv_obj_t * ui_scanButton;
extern lv_obj_t * ui_scanButtonlabel;
void ui_event_econButton(lv_event_t * e);
extern lv_obj_t * ui_econButton;
extern lv_obj_t * ui_econButtonlabel;
extern lv_obj_t * ui_connectFromEEPROMLabel;
void ui_event_TabPage2BT(lv_event_t * e);
extern lv_obj_t * ui_TabPage2BT;
extern lv_obj_t * ui_BtLabel;
void ui_event_BtTextArea(lv_event_t * e);
extern lv_obj_t * ui_BtTextArea;
extern lv_obj_t * ui_BtBitrateLabel;
void ui_event_BtBitrateDropdown(lv_event_t * e);
extern lv_obj_t * ui_BtBitrateDropdown;
void ui_event_BtSave(lv_event_t * e);
extern lv_obj_t * ui_BtSave;
extern lv_obj_t * ui_label20;
void ui_event_BtStop(lv_event_t * e);
extern lv_obj_t * ui_BtStop;
extern lv_obj_t * ui_label1;
void ui_event_BtStart(lv_event_t * e);
extern lv_obj_t * ui_BtStart;
extern lv_obj_t * ui_label2;
void ui_event_TabPage3RFID(lv_event_t * e);
extern lv_obj_t * ui_TabPage3RFID;
extern lv_obj_t * ui_deviceIDlabel;
extern lv_obj_t * ui_versionLabel;
extern lv_obj_t * ui_minfLabel;
extern lv_obj_t * ui_protocolLabel;
extern lv_obj_t * ui_baudLabel;
void ui_event_baudDD(lv_event_t * e);
extern lv_obj_t * ui_baudDD;
extern lv_obj_t * ui_maxfLabel;
extern lv_obj_t * ui_antennaLabel;
extern lv_obj_t * ui_readertypeLabel;
extern lv_obj_t * ui_bandLabel;
void ui_event_banadDD(lv_event_t * e);
extern lv_obj_t * ui_banadDD;
extern lv_obj_t * ui_powerLabel;
void ui_event_powerTextarea(lv_event_t * e);
extern lv_obj_t * ui_powerTextarea;
extern lv_obj_t * ui_scantimeLabel;
void ui_event_scantimeTextarea(lv_event_t * e);
extern lv_obj_t * ui_scantimeTextarea;
void ui_event_beeponSwitch(lv_event_t * e);
extern lv_obj_t * ui_beeponSwitch;
extern lv_obj_t * ui_beeponLabel;
void ui_event_writeButton(lv_event_t * e);
extern lv_obj_t * ui_writeButton;
extern lv_obj_t * ui_writeButtonlabel;
extern lv_obj_t * ui_deviceIDlabel1;
extern lv_obj_t * ui_versionLabel1;
extern lv_obj_t * ui_antennaLabel1;
extern lv_obj_t * ui_maxfLabel1;
extern lv_obj_t * ui_minfLabel1;
extern lv_obj_t * ui_protocolLabel1;
extern lv_obj_t * ui_TabPage4Audio;
extern lv_obj_t * ui_audioLabel;
void ui_event_musicDropdown(lv_event_t * e);
extern lv_obj_t * ui_musicDropdown;
void ui_event_playButton(lv_event_t * e);
extern lv_obj_t * ui_playButton;
extern lv_obj_t * ui_playButtonLabel;
void ui_event_stopButton(lv_event_t * e);
extern lv_obj_t * ui_stopButton;
extern lv_obj_t * ui_stopLabel;
void ui_event_killMusicTask(lv_event_t * e);
extern lv_obj_t * ui_killMusicTask;
extern lv_obj_t * ui_musicInfoLabel;
void ui_event_musicScanButton(lv_event_t * e);
extern lv_obj_t * ui_musicScanButton;
extern lv_obj_t * ui_searchMusiclabel;
extern lv_obj_t * ui_TabPage5Server;
void ui_event_TabPage6Setup(lv_event_t * e);
extern lv_obj_t * ui_TabPage6Setup;
void ui_event_saveScanData(lv_event_t * e);
extern lv_obj_t * ui_saveScanData;
extern lv_obj_t * ui_sleepAfterLabel;
void ui_event_sleepAfterTextarea(lv_event_t * e);
extern lv_obj_t * ui_sleepAfterTextarea;
extern lv_obj_t * ui_saveScanDataLabel;
void ui_event_writeButtonSetupTab(lv_event_t * e);
extern lv_obj_t * ui_writeButtonSetupTab;
extern lv_obj_t * ui_writeButtonlabel1;
extern lv_obj_t * ui_notifyPanel;
void ui_event_notifyPanelclosebutton(lv_event_t * e);
extern lv_obj_t * ui_notifyPanelclosebutton;
extern lv_obj_t * ui_notifyPanelclosebuttonlabel;
extern lv_obj_t * ui_notifyPanellabel;
void ui_event_primaryKeyboard(lv_event_t * e);
extern lv_obj_t * ui_primaryKeyboard;
void ui_event_home(lv_event_t * e);
extern lv_obj_t * ui_home;
extern lv_obj_t * ui_tabNotifyLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_259472572);    // assets\wifi-removebg-resized.png
LV_IMG_DECLARE(ui_img_1743670017);    // assets\noWifi-removebg-redfg.png
LV_IMG_DECLARE(ui_img_settings11_png);    // assets\settings11.png
LV_IMG_DECLARE(ui_img_sd_card_png);    // assets\sd_card.png
LV_IMG_DECLARE(ui_img_home_png);    // assets\home.png
LV_IMG_DECLARE(ui_img_sd_card_error_png);    // assets\sd_card_error.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
