// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void wifi_icon_clicked(lv_event_t * e);
void no_wifi_icon_clicked(lv_event_t * e);
void ssid_dropdown_vchanged(lv_event_t * e);
void connect_function(lv_event_t * e);
void scan_function(lv_event_t * e);
void eeprom_connect(lv_event_t * e);
void bt_bitrate_dd_vchanged(lv_event_t * e);
void save_bt_(lv_event_t * e);
void stop_bt_(lv_event_t * e);
void start_bt_(lv_event_t * e);
void rfid_baud_dd_vchanged(lv_event_t * e);
void rfid_band_dd_vchanged(lv_event_t * e);
void write_rfid(lv_event_t * e);
void audio_dd_value_changed(lv_event_t * e);
void play_music(lv_event_t * e);
void stop_music(lv_event_t * e);
void kill_audio_task(lv_event_t * e);
void search_music(lv_event_t * e);
void save_to_sd_btn_clicked(lv_event_t * e);
void write_setup(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
