// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#include "ui.h"

void wifi_icon_clicked(lv_event_t * e)
{
	// Your code here
}

void no_wifi_icon_clicked(lv_event_t * e)
{
	// Your code here
}

void ssid_dropdown_vchanged(lv_event_t * e)
{
	// Your code here
}

void connect_function(lv_event_t * e)
{
	// Your code here
}

void scan_function(lv_event_t * e)
{
	// Your code here
}

void eeprom_connect(lv_event_t * e)
{
	// Your code here
}

void bt_bitrate_dd_vchanged(lv_event_t * e)
{
	// Your code here
}

void save_bt_(lv_event_t * e)
{
	// Your code here
}

void stop_bt_(lv_event_t * e)
{
	// Your code here
}

void start_bt_(lv_event_t * e)
{
	// Your code here
}

void rfid_baud_dd_vchanged(lv_event_t * e)
{
	// Your code here
}

void rfid_band_dd_vchanged(lv_event_t * e)
{
	// Your code here
}

void write_rfid(lv_event_t * e)
{
	// Your code here
}

void audio_dd_value_changed(lv_event_t * e)
{
	// Your code here
}

void play_music(lv_event_t * e)
{
	// Your code here
}

void stop_music(lv_event_t * e)
{
	// Your code here
}

void kill_audio_task(lv_event_t * e)
{
	// Your code here
}

void search_music(lv_event_t * e)
{
	// Your code here
}

void save_to_sd_btn_clicked(lv_event_t * e)
{
	// Your code here
}

void write_setup(lv_event_t * e)
{
	// Your code here
}
