// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#include "ui.h"

void ui_setupScreen_screen_init(void)
{
    ui_setupScreen = lv_obj_create(NULL);
    lv_obj_set_scroll_dir(ui_setupScreen, LV_DIR_VER);

    ui_mainTab = lv_tabview_create(ui_setupScreen, LV_DIR_TOP, 40);
    lv_obj_set_width(ui_mainTab, lv_pct(100));
    lv_obj_set_height(ui_mainTab, lv_pct(100));
    lv_obj_set_x(ui_mainTab, -1);
    lv_obj_set_y(ui_mainTab, -1);
    lv_obj_set_align(ui_mainTab, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainTab, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_mainTab, lv_color_hex(0xB2E1FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainTab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_mainTab), lv_color_hex(0xB2E1FB),
                              LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_mainTab), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_TabPage1WiFi = lv_tabview_add_tab(ui_mainTab, "WiFi");
    lv_obj_clear_flag(ui_TabPage1WiFi, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ssidLabel = lv_label_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_ssidLabel, lv_pct(13));
    lv_obj_set_height(ui_ssidLabel, lv_pct(10));
    lv_obj_set_x(ui_ssidLabel, lv_pct(-42));
    lv_obj_set_y(ui_ssidLabel, lv_pct(-45));
    lv_obj_set_align(ui_ssidLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ssidLabel, "SSID:");

    ui_ssidDropdown = lv_dropdown_create(ui_TabPage1WiFi);
    lv_dropdown_set_options(ui_ssidDropdown, "not connected");
    lv_obj_set_width(ui_ssidDropdown, lv_pct(49));
    lv_obj_set_height(ui_ssidDropdown, lv_pct(20));
    lv_obj_set_x(ui_ssidDropdown, lv_pct(-7));
    lv_obj_set_y(ui_ssidDropdown, lv_pct(-45));
    lv_obj_set_align(ui_ssidDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ssidDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_passLabel = lv_label_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_passLabel, lv_pct(13));
    lv_obj_set_height(ui_passLabel, lv_pct(10));
    lv_obj_set_x(ui_passLabel, lv_pct(-42));
    lv_obj_set_y(ui_passLabel, lv_pct(-22));
    lv_obj_set_align(ui_passLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passLabel, "Pass:");

    ui_passTextarea = lv_textarea_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_passTextarea, lv_pct(49));
    lv_obj_set_height(ui_passTextarea, lv_pct(20));
    lv_obj_set_x(ui_passTextarea, lv_pct(-7));
    lv_obj_set_y(ui_passTextarea, lv_pct(-22));
    lv_obj_set_align(ui_passTextarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passTextarea, "Placeholder...");



    ui_connectButton = lv_btn_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_connectButton, lv_pct(18));
    lv_obj_set_height(ui_connectButton, lv_pct(15));
    lv_obj_set_x(ui_connectButton, lv_pct(32));
    lv_obj_set_y(ui_connectButton, lv_pct(-22));
    lv_obj_set_align(ui_connectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_connectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_connectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_connectButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectButtonlabel = lv_label_create(ui_connectButton);
    lv_obj_set_width(ui_connectButtonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectButtonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_connectButtonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectButtonlabel, "Conn");

    ui_scanButton = lv_btn_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_scanButton, lv_pct(18));
    lv_obj_set_height(ui_scanButton, lv_pct(15));
    lv_obj_set_x(ui_scanButton, lv_pct(32));
    lv_obj_set_y(ui_scanButton, lv_pct(-45));
    lv_obj_set_align(ui_scanButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scanButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_scanButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scanButtonlabel = lv_label_create(ui_scanButton);
    lv_obj_set_width(ui_scanButtonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scanButtonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_scanButtonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scanButtonlabel, "Scan");

    ui_econButton = lv_btn_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_econButton, lv_pct(18));
    lv_obj_set_height(ui_econButton, lv_pct(15));
    lv_obj_set_x(ui_econButton, lv_pct(0));
    lv_obj_set_y(ui_econButton, lv_pct(20));
    lv_obj_set_align(ui_econButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_econButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_econButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_econButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_econButtonlabel = lv_label_create(ui_econButton);
    lv_obj_set_width(ui_econButtonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_econButtonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_econButtonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_econButtonlabel, "Econ");

    ui_connectFromEEPROMLabel = lv_label_create(ui_TabPage1WiFi);
    lv_obj_set_width(ui_connectFromEEPROMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_connectFromEEPROMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_connectFromEEPROMLabel, lv_pct(0));
    lv_obj_set_y(ui_connectFromEEPROMLabel, lv_pct(2));
    lv_obj_set_align(ui_connectFromEEPROMLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connectFromEEPROMLabel, "Click to connect from EEPROM");

    ui_TabPage2BT = lv_tabview_add_tab(ui_mainTab, "BT");
    lv_obj_clear_flag(ui_TabPage2BT, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_BtLabel = lv_label_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BtLabel, lv_pct(-40));
    lv_obj_set_y(ui_BtLabel, lv_pct(-41));
    lv_obj_set_align(ui_BtLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtLabel, "BT Name: ");

    ui_BtTextArea = lv_textarea_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtTextArea, lv_pct(43));
    lv_obj_set_height(ui_BtTextArea, lv_pct(20));
    lv_obj_set_x(ui_BtTextArea, lv_pct(-5));
    lv_obj_set_y(ui_BtTextArea, lv_pct(-41));
    lv_obj_set_align(ui_BtTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_BtTextArea, "Placeholder...");



    ui_BtBitrateLabel = lv_label_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtBitrateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtBitrateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BtBitrateLabel, lv_pct(-39));
    lv_obj_set_y(ui_BtBitrateLabel, lv_pct(-15));
    lv_obj_set_align(ui_BtBitrateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtBitrateLabel, "Bitrate:");

    ui_BtBitrateDropdown = lv_dropdown_create(ui_TabPage2BT);
    lv_dropdown_set_options(ui_BtBitrateDropdown, "9600\n57600\n115200");
    lv_obj_set_width(ui_BtBitrateDropdown, lv_pct(43));
    lv_obj_set_height(ui_BtBitrateDropdown, lv_pct(20));
    lv_obj_set_x(ui_BtBitrateDropdown, lv_pct(-5));
    lv_obj_set_y(ui_BtBitrateDropdown, lv_pct(-15));
    lv_obj_set_align(ui_BtBitrateDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtBitrateDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_BtSave = lv_btn_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtSave, lv_pct(15));
    lv_obj_set_height(ui_BtSave, lv_pct(13));
    lv_obj_set_x(ui_BtSave, lv_pct(17));
    lv_obj_set_y(ui_BtSave, lv_pct(10));
    lv_obj_set_align(ui_BtSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtSave, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label20 = lv_label_create(ui_BtSave);
    lv_obj_set_width(ui_label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label20, 0);
    lv_obj_set_y(ui_label20, -1);
    lv_obj_set_align(ui_label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label20, "Save");

    ui_BtStop = lv_btn_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtStop, lv_pct(15));
    lv_obj_set_height(ui_BtStop, lv_pct(13));
    lv_obj_set_x(ui_BtStop, lv_pct(-4));
    lv_obj_set_y(ui_BtStop, lv_pct(10));
    lv_obj_set_align(ui_BtStop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtStop, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label1 = lv_label_create(ui_BtStop);
    lv_obj_set_width(ui_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label1, 0);
    lv_obj_set_y(ui_label1, -1);
    lv_obj_set_align(ui_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label1, "Stop");

    ui_BtStart = lv_btn_create(ui_TabPage2BT);
    lv_obj_set_width(ui_BtStart, lv_pct(15));
    lv_obj_set_height(ui_BtStart, lv_pct(13));
    lv_obj_set_x(ui_BtStart, lv_pct(-24));
    lv_obj_set_y(ui_BtStart, lv_pct(10));
    lv_obj_set_align(ui_BtStart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtStart, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label2 = lv_label_create(ui_BtStart);
    lv_obj_set_width(ui_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label2, "Start");

    ui_TabPage3RFID = lv_tabview_add_tab(ui_mainTab, "RFID");
    lv_obj_clear_flag(ui_TabPage3RFID, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_TabPage3RFID, LV_DIR_VER);

    ui_deviceIDlabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_deviceIDlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceIDlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceIDlabel, lv_pct(-34));
    lv_obj_set_y(ui_deviceIDlabel, lv_pct(-44));
    lv_obj_set_align(ui_deviceIDlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deviceIDlabel, "Dev. ID:");

    ui_versionLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_versionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_versionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_versionLabel, lv_pct(13));
    lv_obj_set_y(ui_versionLabel, lv_pct(-44));
    lv_obj_set_align(ui_versionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_versionLabel, "Ver:");

    ui_minfLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_minfLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minfLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minfLabel, lv_pct(11));
    lv_obj_set_y(ui_minfLabel, lv_pct(8));
    lv_obj_set_align(ui_minfLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minfLabel, "Min f.");

    ui_protocolLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_protocolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_protocolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_protocolLabel, lv_pct(-40));
    lv_obj_set_y(ui_protocolLabel, lv_pct(21));
    lv_obj_set_align(ui_protocolLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_protocolLabel, "Protocol:");

    ui_baudLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_baudLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_baudLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_baudLabel, lv_pct(11));
    lv_obj_set_y(ui_baudLabel, lv_pct(-28));
    lv_obj_set_align(ui_baudLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_baudLabel, "Baud.");

    ui_baudDD = lv_dropdown_create(ui_TabPage3RFID);
    lv_dropdown_set_options(ui_baudDD, "57600\n115200");
    lv_obj_set_width(ui_baudDD, lv_pct(26));
    lv_obj_set_height(ui_baudDD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_baudDD, lv_pct(32));
    lv_obj_set_y(ui_baudDD, lv_pct(-28));
    lv_obj_set_align(ui_baudDD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_baudDD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_maxfLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_maxfLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxfLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxfLabel, lv_pct(11));
    lv_obj_set_y(ui_maxfLabel, lv_pct(21));
    lv_obj_set_align(ui_maxfLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_maxfLabel, "Max f.");

    ui_antennaLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_antennaLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_antennaLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_antennaLabel, lv_pct(-40));
    lv_obj_set_y(ui_antennaLabel, lv_pct(8));
    lv_obj_set_align(ui_antennaLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_antennaLabel, "Antenna:");

    ui_readertypeLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_readertypeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_readertypeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_readertypeLabel, lv_pct(-28));
    lv_obj_set_y(ui_readertypeLabel, lv_pct(67));
    lv_obj_set_align(ui_readertypeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_readertypeLabel, "Reader");

    ui_bandLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_bandLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bandLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_bandLabel, lv_pct(11));
    lv_obj_set_y(ui_bandLabel, lv_pct(-10));
    lv_obj_set_align(ui_bandLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bandLabel, "Band.");

    ui_banadDD = lv_dropdown_create(ui_TabPage3RFID);
    lv_dropdown_set_options(ui_banadDD, "USA\nKorean\nEU\nChinese");
    lv_obj_set_width(ui_banadDD, lv_pct(26));
    lv_obj_set_height(ui_banadDD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_banadDD, lv_pct(32));
    lv_obj_set_y(ui_banadDD, lv_pct(-9));
    lv_obj_set_align(ui_banadDD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_banadDD, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_powerLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_powerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerLabel, lv_pct(-38));
    lv_obj_set_y(ui_powerLabel, lv_pct(-10));
    lv_obj_set_align(ui_powerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_powerLabel, "Power(dB):");

    ui_powerTextarea = lv_textarea_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_powerTextarea, lv_pct(25));
    lv_obj_set_height(ui_powerTextarea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powerTextarea, lv_pct(-11));
    lv_obj_set_y(ui_powerTextarea, lv_pct(-9));
    lv_obj_set_align(ui_powerTextarea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_powerTextarea, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_powerTextarea, LV_SCROLLBAR_MODE_OFF);



    ui_scantimeLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_scantimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scantimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scantimeLabel, lv_pct(-39));
    lv_obj_set_y(ui_scantimeLabel, lv_pct(-28));
    lv_obj_set_align(ui_scantimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scantimeLabel, "Scan t.(ms):");

    ui_scantimeTextarea = lv_textarea_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_scantimeTextarea, lv_pct(25));
    lv_obj_set_height(ui_scantimeTextarea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scantimeTextarea, lv_pct(-11));
    lv_obj_set_y(ui_scantimeTextarea, lv_pct(-28));
    lv_obj_set_align(ui_scantimeTextarea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scantimeTextarea,
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_scantimeTextarea, LV_SCROLLBAR_MODE_OFF);



    ui_beeponSwitch = lv_switch_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_beeponSwitch, lv_pct(11));
    lv_obj_set_height(ui_beeponSwitch, lv_pct(10));
    lv_obj_set_x(ui_beeponSwitch, lv_pct(-21));
    lv_obj_set_y(ui_beeponSwitch, lv_pct(36));
    lv_obj_set_align(ui_beeponSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_beeponSwitch, lv_color_hex(0xCE9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_beeponSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_beeponLabel = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_beeponLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_beeponLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_beeponLabel, lv_pct(-40));
    lv_obj_set_y(ui_beeponLabel, lv_pct(36));
    lv_obj_set_align(ui_beeponLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_beeponLabel, "beep on");

    ui_writeButton = lv_btn_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_writeButton, lv_pct(20));
    lv_obj_set_height(ui_writeButton, lv_pct(16));
    lv_obj_set_x(ui_writeButton, lv_pct(40));
    lv_obj_set_y(ui_writeButton, lv_pct(43));
    lv_obj_set_align(ui_writeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_writeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_writeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_writeButton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_writeButtonlabel = lv_label_create(ui_writeButton);
    lv_obj_set_width(ui_writeButtonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_writeButtonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_writeButtonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_writeButtonlabel, "Write");

    ui_deviceIDlabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_deviceIDlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deviceIDlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deviceIDlabel1, lv_pct(27));
    lv_obj_set_y(ui_deviceIDlabel1, lv_pct(2));
    lv_label_set_text(ui_deviceIDlabel1, "");

    ui_versionLabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_versionLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_versionLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_versionLabel1, lv_pct(70));
    lv_obj_set_y(ui_versionLabel1, lv_pct(3));
    lv_label_set_text(ui_versionLabel1, "");

    ui_antennaLabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_antennaLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_antennaLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_antennaLabel1, lv_pct(23));
    lv_obj_set_y(ui_antennaLabel1, lv_pct(53));
    lv_label_set_text(ui_antennaLabel1, "");

    ui_maxfLabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_maxfLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_maxfLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_maxfLabel1, lv_pct(69));
    lv_obj_set_y(ui_maxfLabel1, lv_pct(21));
    lv_obj_set_align(ui_maxfLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_maxfLabel1, "");

    ui_minfLabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_minfLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minfLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minfLabel1, lv_pct(69));
    lv_obj_set_y(ui_minfLabel1, lv_pct(8));
    lv_obj_set_align(ui_minfLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_minfLabel1, "");

    ui_protocolLabel1 = lv_label_create(ui_TabPage3RFID);
    lv_obj_set_width(ui_protocolLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_protocolLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_protocolLabel1, lv_pct(22));
    lv_obj_set_y(ui_protocolLabel1, lv_pct(21));
    lv_obj_set_align(ui_protocolLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_protocolLabel1, "");

    ui_TabPage4Audio = lv_tabview_add_tab(ui_mainTab, "Audio");
    lv_obj_clear_flag(ui_TabPage4Audio, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_audioLabel = lv_label_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_audioLabel, lv_pct(32));
    lv_obj_set_height(ui_audioLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audioLabel, lv_pct(-34));
    lv_obj_set_y(ui_audioLabel, lv_pct(-38));
    lv_obj_set_align(ui_audioLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audioLabel, "Select Track");

    ui_musicDropdown = lv_dropdown_create(ui_TabPage4Audio);
    lv_dropdown_set_options(ui_musicDropdown, "Select audio.");
    lv_obj_set_width(ui_musicDropdown, lv_pct(65));
    lv_obj_set_height(ui_musicDropdown, lv_pct(20));
    lv_obj_set_x(ui_musicDropdown, lv_pct(15));
    lv_obj_set_y(ui_musicDropdown, lv_pct(-38));
    lv_obj_set_align(ui_musicDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_playButton = lv_btn_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_playButton, lv_pct(20));
    lv_obj_set_height(ui_playButton, lv_pct(18));
    lv_obj_set_x(ui_playButton, lv_pct(0));
    lv_obj_set_y(ui_playButton, lv_pct(7));
    lv_obj_set_align(ui_playButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_playButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_playButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_playButtonLabel = lv_label_create(ui_playButton);
    lv_obj_set_width(ui_playButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_playButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_playButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_playButtonLabel, "play");

    ui_stopButton = lv_btn_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_stopButton, lv_pct(20));
    lv_obj_set_height(ui_stopButton, lv_pct(18));
    lv_obj_set_x(ui_stopButton, lv_pct(25));
    lv_obj_set_y(ui_stopButton, lv_pct(7));
    lv_obj_set_align(ui_stopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_stopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_stopLabel = lv_label_create(ui_stopButton);
    lv_obj_set_width(ui_stopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_stopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stopLabel, "stop");

    ui_killMusicTask = lv_label_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_killMusicTask, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_killMusicTask, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_killMusicTask, lv_pct(42));
    lv_obj_set_y(ui_killMusicTask, lv_pct(46));
    lv_obj_set_align(ui_killMusicTask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_killMusicTask, "Kill task");

    ui_musicInfoLabel = lv_label_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_musicInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_musicInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_musicInfoLabel, lv_pct(8));
    lv_obj_set_y(ui_musicInfoLabel, lv_pct(-15));
    lv_obj_set_align(ui_musicInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_musicInfoLabel, "Music info.");

    ui_musicScanButton = lv_btn_create(ui_TabPage4Audio);
    lv_obj_set_width(ui_musicScanButton, lv_pct(20));
    lv_obj_set_height(ui_musicScanButton, lv_pct(18));
    lv_obj_set_x(ui_musicScanButton, lv_pct(-25));
    lv_obj_set_y(ui_musicScanButton, lv_pct(7));
    lv_obj_set_align(ui_musicScanButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_musicScanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_musicScanButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_searchMusiclabel = lv_label_create(ui_musicScanButton);
    lv_obj_set_width(ui_searchMusiclabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_searchMusiclabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_searchMusiclabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_searchMusiclabel, "Search");

    ui_TabPage5Server = lv_tabview_add_tab(ui_mainTab, "Server");
    lv_obj_clear_flag(ui_TabPage5Server,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_TabPage6Setup = lv_tabview_add_tab(ui_mainTab, "Setup");
    lv_obj_clear_flag(ui_TabPage6Setup, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_saveScanData = lv_switch_create(ui_TabPage6Setup);
    lv_obj_set_width(ui_saveScanData, lv_pct(11));
    lv_obj_set_height(ui_saveScanData, lv_pct(10));
    lv_obj_set_x(ui_saveScanData, lv_pct(20));
    lv_obj_set_y(ui_saveScanData, lv_pct(-23));
    lv_obj_set_align(ui_saveScanData, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_saveScanData, lv_color_hex(0xCE9F9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveScanData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_sleepAfterLabel = lv_label_create(ui_TabPage6Setup);
    lv_obj_set_width(ui_sleepAfterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepAfterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sleepAfterLabel, lv_pct(-22));
    lv_obj_set_y(ui_sleepAfterLabel, lv_pct(-44));
    lv_obj_set_align(ui_sleepAfterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sleepAfterLabel, "device will sleep in(min)");

    ui_sleepAfterTextarea = lv_textarea_create(ui_TabPage6Setup);
    lv_obj_set_width(ui_sleepAfterTextarea, lv_pct(40));
    lv_obj_set_height(ui_sleepAfterTextarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_sleepAfterTextarea, lv_pct(31));
    lv_obj_set_y(ui_sleepAfterTextarea, lv_pct(-43));
    lv_obj_set_align(ui_sleepAfterTextarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_sleepAfterTextarea, "e.g: 1");



    ui_saveScanDataLabel = lv_label_create(ui_TabPage6Setup);
    lv_obj_set_width(ui_saveScanDataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveScanDataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_saveScanDataLabel, lv_pct(-20));
    lv_obj_set_y(ui_saveScanDataLabel, lv_pct(-23));
    lv_obj_set_align(ui_saveScanDataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveScanDataLabel, "Save scan data in SD card");

    ui_writeButtonSetupTab = lv_btn_create(ui_TabPage6Setup);
    lv_obj_set_width(ui_writeButtonSetupTab, lv_pct(20));
    lv_obj_set_height(ui_writeButtonSetupTab, lv_pct(16));
    lv_obj_set_x(ui_writeButtonSetupTab, lv_pct(40));
    lv_obj_set_y(ui_writeButtonSetupTab, lv_pct(43));
    lv_obj_set_align(ui_writeButtonSetupTab, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_writeButtonSetupTab, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_writeButtonSetupTab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_writeButtonSetupTab, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_writeButtonlabel1 = lv_label_create(ui_writeButtonSetupTab);
    lv_obj_set_width(ui_writeButtonlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_writeButtonlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_writeButtonlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_writeButtonlabel1, "Write");

    ui_notifyPanel = lv_obj_create(ui_setupScreen);
    lv_obj_set_width(ui_notifyPanel, lv_pct(58));
    lv_obj_set_height(ui_notifyPanel, lv_pct(46));
    lv_obj_set_x(ui_notifyPanel, -2);
    lv_obj_set_y(ui_notifyPanel, -12);
    lv_obj_set_align(ui_notifyPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notifyPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_notifyPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_notifyPanel, lv_color_hex(0x655151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_notifyPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_notifyPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_notifyPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_notifyPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_notifyPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanelclosebutton = lv_btn_create(ui_notifyPanel);
    lv_obj_set_width(ui_notifyPanelclosebutton, lv_pct(23));
    lv_obj_set_height(ui_notifyPanelclosebutton, lv_pct(25));
    lv_obj_set_x(ui_notifyPanelclosebutton, 71);
    lv_obj_set_y(ui_notifyPanelclosebutton, -40);
    lv_obj_set_align(ui_notifyPanelclosebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_notifyPanelclosebutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_notifyPanelclosebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_notifyPanelclosebutton, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanelclosebuttonlabel = lv_label_create(ui_notifyPanelclosebutton);
    lv_obj_set_width(ui_notifyPanelclosebuttonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notifyPanelclosebuttonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notifyPanelclosebuttonlabel, lv_pct(-5));
    lv_obj_set_y(ui_notifyPanelclosebuttonlabel, lv_pct(0));
    lv_obj_set_align(ui_notifyPanelclosebuttonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notifyPanelclosebuttonlabel, "close");
    lv_obj_set_style_text_font(ui_notifyPanelclosebuttonlabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanellabel = lv_label_create(ui_notifyPanel);
    lv_obj_set_width(ui_notifyPanellabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_notifyPanellabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_notifyPanellabel, 2);
    lv_obj_set_y(ui_notifyPanellabel, 1);
    lv_obj_set_align(ui_notifyPanellabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notifyPanellabel, "info.");

    ui_primaryKeyboard = lv_keyboard_create(ui_setupScreen);
    lv_obj_set_width(ui_primaryKeyboard, 300);
    lv_obj_set_height(ui_primaryKeyboard, 120);
    lv_obj_set_x(ui_primaryKeyboard, 1);
    lv_obj_set_y(ui_primaryKeyboard, 64);
    lv_obj_set_align(ui_primaryKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_primaryKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_home = lv_img_create(ui_setupScreen);
    lv_img_set_src(ui_home, &ui_img_home_png);
    lv_obj_set_width(ui_home, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_home, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_home, -144);
    lv_obj_set_y(ui_home, 104);
    lv_obj_set_align(ui_home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_home, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_home, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_tabNotifyLabel = lv_label_create(ui_setupScreen);
    lv_obj_set_width(ui_tabNotifyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tabNotifyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tabNotifyLabel, lv_pct(-1));
    lv_obj_set_y(ui_tabNotifyLabel, lv_pct(-2));
    lv_obj_set_align(ui_tabNotifyLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_tabNotifyLabel, "");

    lv_obj_add_event_cb(ui_ssidDropdown, ui_event_ssidDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passTextarea, ui_event_passTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectButton, ui_event_connectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scanButton, ui_event_scanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_econButton, ui_event_econButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage1WiFi, ui_event_TabPage1WiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtTextArea, ui_event_BtTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtBitrateDropdown, ui_event_BtBitrateDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtSave, ui_event_BtSave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtStop, ui_event_BtStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtStart, ui_event_BtStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage2BT, ui_event_TabPage2BT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_baudDD, ui_event_baudDD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_banadDD, ui_event_banadDD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_powerTextarea, ui_event_powerTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scantimeTextarea, ui_event_scantimeTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_beeponSwitch, ui_event_beeponSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_writeButton, ui_event_writeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage3RFID, ui_event_TabPage3RFID, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicDropdown, ui_event_musicDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_playButton, ui_event_playButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_stopButton, ui_event_stopButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_killMusicTask, ui_event_killMusicTask, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_musicScanButton, ui_event_musicScanButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveScanData, ui_event_saveScanData, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sleepAfterTextarea, ui_event_sleepAfterTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_writeButtonSetupTab, ui_event_writeButtonSetupTab, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TabPage6Setup, ui_event_TabPage6Setup, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainTab, ui_event_mainTab, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_notifyPanelclosebutton, ui_event_notifyPanelclosebutton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_primaryKeyboard, ui_passTextarea);
    lv_obj_add_event_cb(ui_primaryKeyboard, ui_event_primaryKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}
